// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ValidaCredenciaisHandlerFunc turns a function with the right signature into a valida credenciais handler
type ValidaCredenciaisHandlerFunc func(ValidaCredenciaisParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ValidaCredenciaisHandlerFunc) Handle(params ValidaCredenciaisParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ValidaCredenciaisHandler interface for that can handle valid valida credenciais params
type ValidaCredenciaisHandler interface {
	Handle(ValidaCredenciaisParams, interface{}) middleware.Responder
}

// NewValidaCredenciais creates a new http.Handler for the valida credenciais operation
func NewValidaCredenciais(ctx *middleware.Context, handler ValidaCredenciaisHandler) *ValidaCredenciais {
	return &ValidaCredenciais{Context: ctx, Handler: handler}
}

/*ValidaCredenciais swagger:route POST /auth auth validaCredenciais

Valida um usuário e senha

O sistema valida os usuários e senha fazendo cache de dados do usuário por 10 segundos. Em caso de troca de senha é necesário aguardar esse tempo para realizar novas tentativas.
 Requisições do mesmo IP ou usuário com a senha errada 5 vezes entrão na fila de bloqueio e permanecem lá por 3 min. *Podendomos futuramente colocar o IP do cliente no FireWall do SO.*
 O sistema de autenticação tem como restrição senhas de no mínimo 6 caracteres e no máximo 200.
 As autenticação tem como resposta OK, 200, ou erro de autenticação.


*/
type ValidaCredenciais struct {
	Context *middleware.Context
	Handler ValidaCredenciaisHandler
}

func (o *ValidaCredenciais) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewValidaCredenciaisParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
