// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/hallanneves/autenticador/models"
)

// ValidaAutenticacaoCreatedCode is the HTTP code returned for type ValidaAutenticacaoCreated
const ValidaAutenticacaoCreatedCode int = 201

/*ValidaAutenticacaoCreated Status 200

swagger:response validaAutenticacaoCreated
*/
type ValidaAutenticacaoCreated struct {
}

// NewValidaAutenticacaoCreated creates ValidaAutenticacaoCreated with default headers values
func NewValidaAutenticacaoCreated() *ValidaAutenticacaoCreated {

	return &ValidaAutenticacaoCreated{}
}

// WriteResponse to the client
func (o *ValidaAutenticacaoCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// ValidaAutenticacaoInternalServerErrorCode is the HTTP code returned for type ValidaAutenticacaoInternalServerError
const ValidaAutenticacaoInternalServerErrorCode int = 500

/*ValidaAutenticacaoInternalServerError Status 500

swagger:response validaAutenticacaoInternalServerError
*/
type ValidaAutenticacaoInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Erro `json:"body,omitempty"`
}

// NewValidaAutenticacaoInternalServerError creates ValidaAutenticacaoInternalServerError with default headers values
func NewValidaAutenticacaoInternalServerError() *ValidaAutenticacaoInternalServerError {

	return &ValidaAutenticacaoInternalServerError{}
}

// WithPayload adds the payload to the valida autenticacao internal server error response
func (o *ValidaAutenticacaoInternalServerError) WithPayload(payload *models.Erro) *ValidaAutenticacaoInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the valida autenticacao internal server error response
func (o *ValidaAutenticacaoInternalServerError) SetPayload(payload *models.Erro) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ValidaAutenticacaoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
