// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Autenticador
Essa API foi desenvolvida para gerenciar o servico de autenticacao de usuario em um microserviço genérico.
 É necesário um tokem de acesso para a aplicação acessar a API de autenticação. Pode ser removido mediante analise do projeto.


    Schemes:
      http
      https
    Host: localhost
    BasePath: /v1
    Version: 1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
